# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 391)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowOpacity(1.0)
        
        self.currfrom = QtWidgets.QComboBox(Dialog)
        self.currfrom.setGeometry(QtCore.QRect(230, 210, 231, 61))
        self.currfrom.setObjectName("currfrom")
        self.currto = QtWidgets.QComboBox(Dialog)
        self.currto.setGeometry(QtCore.QRect(230, 300, 231, 61))
        self.currto.setObjectName("currto")
        self.currfrommoney = QtWidgets.QLineEdit(Dialog)
        self.currfrommoney.setGeometry(QtCore.QRect(10, 210, 211, 61))
        self.currfrommoney.setObjectName("currfrommoney")
        self.currtomoney = QtWidgets.QLineEdit(Dialog)
        self.currtomoney.setGeometry(QtCore.QRect(10, 300, 211, 61))
        self.currtomoney.setObjectName("currtomoney")
        self.bigmoney = QtWidgets.QLabel(Dialog)
        self.bigmoney.setGeometry(QtCore.QRect(10, 115, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.bigmoney.setFont(font)
        self.bigmoney.setObjectName("bigmoney")
        self.equalsmoney = QtWidgets.QLabel(Dialog)
        self.equalsmoney.setGeometry(QtCore.QRect(10, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.equalsmoney.setFont(font)
        self.equalsmoney.setObjectName("equalsmoney")
        self.graph = QtWidgets.QWidget(Dialog)
        self.graph.setGeometry(QtCore.QRect(240, 10, 221, 171))
        self.graph.setObjectName("graph")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Currency Converter"))
        self.bigmoney.setText(_translate("Dialog", "TextLabel"))
        self.equalsmoney.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
